-- LazyGit in a floating terminal.
--
--   <leader>gg / :LazyGit      LazyGit for the current buffer's repository
--   <leader>gf / :LazyGitFile  LazyGit filtered to the current file's history
--
-- Settings for the LazyGit launched here are written to a generated config
-- file and passed via LG_CONFIG_FILE, after the user's own config.yml, so
-- standalone `lazygit` is unaffected. `e` in LazyGit opens the file in this
-- Neovim (see scripts/lazygit-edit.lua) instead of a nested one.
--
-- See docs/modules/ROOT/pages/editor/git/lazygit.adoc for the full guide.

local M = {}

local state = { win = nil, prev_win = nil }

-- scripts/lazygit-edit.lua, resolved from this file's location.
local EDIT_SCRIPT = vim.fs.normalize(
  debug.getinfo(1, "S").source:sub(2):gsub("lua/config/lazygit%.lua$", "") .. "scripts/lazygit-edit.lua"
)

--- Run a command and return its trimmed stdout, or nil on failure.
---@param cmd string[]
---@return string?
local function run(cmd)
  local ok, res = pcall(function()
    return vim.system(cmd, { text = true }):wait(3000)
  end)
  if not ok or res.code ~= 0 then
    return nil
  end
  local out = vim.trim(res.stdout or "")
  return out ~= "" and out or nil
end

---@param dir string
---@return string?
local function git_root(dir)
  return run({ "git", "-C", dir, "rev-parse", "--show-toplevel" })
end

--- Repository for the current buffer's file, else for the cwd.
---@return string?
local function find_root()
  local file = vim.api.nvim_buf_get_name(0)
  if file ~= "" and vim.bo.buftype == "" then
    local root = git_root(vim.fs.dirname(file))
    if root then
      return root
    end
  end
  return git_root(vim.fn.getcwd())
end

--- Path of the binary LazyGit should run to reach this Neovim. Under an
--- AppImage, v:progpath points inside its temporary mount, so prefer $APPIMAGE.
---@return string
local function nvim_bin()
  return vim.env.APPIMAGE or vim.v.progpath
end

---@param colors table<string, any>
---@return string[]
local function theme_lines(colors)
  local function c(...)
    for _, v in ipairs({ ... }) do
      if type(v) == "string" and v:match("^#%x%x%x%x%x%x$") then
        return v
      end
    end
  end
  local entries = {
    { "activeBorderColor", c(colors.orange), true },
    { "inactiveBorderColor", c(colors.border_highlight, colors.blue0) },
    { "searchingActiveBorderColor", c(colors.orange), true },
    { "optionsTextColor", c(colors.blue) },
    { "selectedLineBgColor", c(colors.bg_visual, colors.bg_highlight) },
    { "inactiveViewSelectedLineBgColor", c(colors.bg_highlight) },
    { "cherryPickedCommitFgColor", c(colors.blue) },
    { "cherryPickedCommitBgColor", c(colors.magenta) },
    { "markedBaseCommitFgColor", c(colors.blue) },
    { "markedBaseCommitBgColor", c(colors.yellow) },
    { "unstagedChangesColor", c(colors.red1, colors.red) },
    { "defaultFgColor", c(colors.fg) },
  }
  local lines = { "gui:", "  theme:" }
  for _, e in ipairs(entries) do
    if e[2] then
      table.insert(lines, ("    %s: [%q%s]"):format(e[1], e[2], e[3] and ', "bold"' or ""))
    end
  end
  return #lines > 2 and lines or {}
end

--- TokyoNight palette for the active style, or nil when it does not apply.
---@return table?
local function palette()
  if not vim.o.termguicolors then
    return nil
  end
  local style = (vim.g.colors_name or ""):match("^tokyonight%-(%a+)$")
  if not style then
    return nil
  end
  local ok, colors = pcall(function()
    return require("tokyonight.colors").setup({ style = style })
  end)
  return ok and colors or nil
end

--- Write the generated LazyGit config and return its path.
---@return string
local function write_config()
  local edit = '"$LAZYGIT_NVIM_BIN" --clean -l "$LAZYGIT_EDIT_SCRIPT"'
  local lines = {
    "# Generated by lua/config/lazygit.lua on each launch. Do not edit.",
    "os:",
    "  edit: '" .. edit .. " {{filename}}'",
    "  editAtLine: '" .. edit .. " --line {{line}} {{filename}}'",
    -- Waiting edits (e.g. commit messages) need a blocking editor, so these
    -- start a nested Neovim in the float by path rather than via `nvim`.
    "  editAtLineAndWait: '\"$LAZYGIT_NVIM_BIN\" +{{line}} -- {{filename}}'",
    "  editInTerminal: false",
    "  openDirInEditor: '" .. edit .. " {{dir}}'",
  }
  local colors = palette()
  if colors then
    vim.list_extend(lines, theme_lines(colors))
  end
  local dir = vim.fn.stdpath("state") .. "/lazygit"
  vim.fn.mkdir(dir, "p")
  local path = dir .. "/nvim.yml"
  vim.fn.writefile(lines, path)
  return path
end

--- LG_CONFIG_FILE value: the user's config.yml (if any), then the generated one.
---@param generated string
---@return string
local function config_files(generated)
  if M._user_config == nil then
    local dir = run({ "lazygit", "--print-config-dir" })
    local path = dir and (dir .. "/config.yml")
    M._user_config = (path and vim.uv.fs_stat(path)) and path or false
  end
  if M._user_config then
    return M._user_config .. "," .. generated
  end
  return generated
end

local function win_config()
  local width = math.floor(vim.o.columns * 0.9)
  local height = math.floor(vim.o.lines * 0.9)
  return {
    relative = "editor",
    width = width,
    height = height,
    row = math.floor((vim.o.lines - height) / 2),
    col = math.floor((vim.o.columns - width) / 2),
    style = "minimal",
    border = "rounded",
    title = " LazyGit ",
    title_pos = "center",
  }
end

local function close()
  if state.win and vim.api.nvim_win_is_valid(state.win) then
    vim.api.nvim_win_close(state.win, true)
  end
  state.win = nil
end

--- Bring the editor up to date with whatever LazyGit changed.
local function refresh()
  pcall(vim.cmd.checktime)
  if package.loaded.gitsigns then
    pcall(require("gitsigns").refresh)
  end
  if package.loaded["nvim-tree"] then
    pcall(function()
      require("nvim-tree.api").tree.reload()
    end)
  end
end

---@param args string[]
---@param root string
local function open(args, root)
  if state.win and vim.api.nvim_win_is_valid(state.win) then
    vim.api.nvim_set_current_win(state.win)
    vim.cmd.startinsert()
    return
  end

  state.prev_win = vim.api.nvim_get_current_win()
  local buf = vim.api.nvim_create_buf(false, true)
  state.win = vim.api.nvim_open_win(buf, true, win_config())
  vim.bo[buf].bufhidden = "wipe"

  vim.fn.jobstart(vim.list_extend({ "lazygit" }, args), {
    term = true,
    cwd = root,
    env = {
      LG_CONFIG_FILE = config_files(write_config()),
      LAZYGIT_NVIM_BIN = nvim_bin(),
      LAZYGIT_EDIT_SCRIPT = EDIT_SCRIPT,
    },
    on_exit = function()
      vim.schedule(function()
        close()
        refresh()
      end)
    end,
  })

  -- The global terminal <Esc> leaves terminal mode; LazyGit needs the key.
  vim.keymap.set("t", "<Esc>", "<Esc>", { buffer = buf, noremap = true, desc = "LazyGit: pass <Esc> through" })
  vim.cmd.startinsert()
end

---@return boolean
local function have_lazygit()
  if vim.fn.executable("lazygit") == 1 then
    return true
  end
  vim.notify("LazyGit: `lazygit` not found on $PATH. See getting-started.adoc for the install.", vim.log.levels.ERROR)
  return false
end

--- LazyGit for the current repository.
function M.open()
  if not have_lazygit() then
    return
  end
  local root = find_root()
  if not root then
    vim.notify("LazyGit: not inside a git repository", vim.log.levels.WARN)
    return
  end
  open({}, root)
end

--- LazyGit filtered to the current file's history.
function M.open_file()
  if not have_lazygit() then
    return
  end
  local file = vim.api.nvim_buf_get_name(0)
  if file == "" or vim.bo.buftype ~= "" then
    vim.notify("LazyGit: buffer has no file", vim.log.levels.WARN)
    return
  end
  file = vim.uv.fs_realpath(file) or file
  local root = git_root(vim.fs.dirname(file))
  if not root then
    vim.notify("LazyGit: " .. file .. " is not inside a git repository", vim.log.levels.WARN)
    return
  end
  root = vim.uv.fs_realpath(root) or root
  open({ "-f", file:sub(#root + 2) }, root)
end

--- Called from scripts/lazygit-edit.lua when `e` is pressed in LazyGit.
--- The first file is shown; any others (`e` on a directory row) are added
--- to the buffer list.
---@param files string[]  absolute paths
---@param line? integer
function M.edit(files, line)
  vim.schedule(function()
    close()
    if state.prev_win and vim.api.nvim_win_is_valid(state.prev_win) then
      vim.api.nvim_set_current_win(state.prev_win)
    end
    vim.cmd.stopinsert()
    for i = #files, 2, -1 do
      vim.cmd.badd(vim.fn.fnameescape(files[i]))
    end
    vim.cmd.edit(vim.fn.fnameescape(files[1]))
    if line and line > 0 then
      pcall(vim.api.nvim_win_set_cursor, 0, { line, 0 })
    end
  end)
end

function M.setup()
  vim.api.nvim_create_user_command("LazyGit", M.open, { desc = "LazyGit: repository" })
  vim.api.nvim_create_user_command("LazyGitFile", M.open_file, { desc = "LazyGit: current file history" })
  vim.keymap.set("n", "<leader>gg", M.open, { noremap = true, silent = true, desc = "LazyGit" })
  vim.keymap.set("n", "<leader>gf", M.open_file, { noremap = true, silent = true, desc = "LazyGit: file history" })

  vim.api.nvim_create_autocmd("VimResized", {
    group = vim.api.nvim_create_augroup("lazygit_float", { clear = true }),
    callback = function()
      if state.win and vim.api.nvim_win_is_valid(state.win) then
        vim.api.nvim_win_set_config(state.win, win_config())
      end
    end,
  })
end

return M
