return { 
  "airblade/vim-gitgutter",
  "dense-analysis/ale",
  "godlygeek/tabular",
  "mattn/emmet-vim",
  "OmniSharp/omnisharp-vim",
  "OrangeT/vim-csharp",
  "Shougo/neosnippet.vim",
  "Shougo/neosnippet-snippets",
  "tpope/vim-fugitive",
  "tpope/vim-repeat",
  "tpope/vim-sensible",
  "tpope/vim-surround",
  "tpope/vim-unimpaired",
  "vim-airline/vim-airline",
  -- f-sharp tooling
  -- "autozimu/LanguageClient-neovim", branch = "next", build = "bash install.sh",
  -- "ionide/Ionide-vim",
  -- "junegunn/fzf",
}
